### ISSUE TITLE
Accurate browserAPI extraction in metadata.

### ISSUE THREAD

**Issue by 1natsu172** [wxt-dev/examples#6]
I would rather update the code so the actual API you use (`browser.runtime.xyz`) shows up.

_Originally posted by @aklinker1 in https://github.com/wxt-dev/examples/pull/4#discussion_r1712675374_
            

refer to: #4 #5

**Comment by 1natsu172** [comment]
https://github.com/GoogleChrome/chrome-extensions-samples/blob/f33eb566803f6c98786efde7232a688d67211d2b/.repo/sample-list-generator/src/libs/api-detector.ts

It would be fine to traverse it in the same way. If not in a hurry, I can give it a try.

**Comment by aklinker1** [comment]
Yeah, I'm down to try something like that!
